"""rename address

Revision ID: 136f37afe65b
Revises: 9bc689c3e310
Create Date: 2024-05-01 17:13:13.035966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136f37afe65b'
down_revision = '9bc689c3e310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
